server:
  port: ${PORT:8082}

spring:
  application:
    name: store-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/subarnapasal}
    username: ${DB_USER:subarnapasal}
    password: ${DB_PASSWORD:subarnapasal}
  sql:
    init:
      mode: always

rates:
  base-url: ${RATES_SERVICE_URL:http://localhost:8083}
auth:
  base-url: ${AUTH_SERVICE_URL:http://localhost:8081}
